// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_users.sql

package database

import (
	"context"
)

const deletUsers = `-- name: DeletUsers :exec
DELETE FROM users
`

func (q *Queries) DeletUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletUsers)
	return err
}
